### PR TITLE
Send content ids with redirects

### PR DESCRIPTION
**Pull request by elliotcm**
Required for https://github.com/alphagov/govuk-content-schemas/pull/148

### CODE REVIEW

**Comment by jamiecobbett** [comment]
Would you mind adding a test that validates against the schema and hooking it up so that it gets built whenever there is a change to the schemas [as per the documentation](https://github.com/alphagov/govuk-content-schemas/blob/master/docs/contract-testing-howto.md)?

**Comment by elliotcm** [comment]
@jamiecobbett Yep, we'll do that as another pull request.

**Comment by tuzz** [comment]
It made sense to put this change on top, otherwise we'd have mutually dependent pull requests.

**Comment by tuzz** [comment]
I don't have Jenkins permissions to complete the final steps [here](https://github.com/alphagov/govuk-content-schemas/blob/master/docs/contract-testing-howto.md#setting-up-the-ci-builds).

I've done as much as I can – i.e. the jenkins-schema.sh has been set up and just needs to be called form this job as per the instructions.

**Comment by elliotcm** [comment]
@tuzz Done.

**Comment by tuzz** [comment]
@elliotcm Thanks!

**Pull request merged**
