### PR TITLE
Add the ability for short URLs to be edited by admins

### PR DESCRIPTION
**Pull request by issyl0**
- To do this, change some of the wording of the `new` form and make it
  into a `form` partial.
- Test this new behaviour.

Here are some screenshots of the process.

Before:

screen shot 2015-05-01 at 15 29 47

During:

screen shot 2015-05-01 at 15 30 00

After:

screen shot 2015-05-01 at 15 30 04

### CODE REVIEW

**Comment by alext** [comment]
This won't actually make any change to the live site.  There's nothing to send the updated redirect to the publishing-api.

Additionally, if we allow editing the source path, this gets more tricky as we need to deal with removing/replacing the old source.  I'd suggest that we don't allow editing the source path, and handle those cases by creating a new short URL.

**Comment by bradleywright** [comment]
The code to push to router-api:

https://github.com/alphagov/short-url-manager/blob/master/app/models/short_url_request.rb#L26-L35

**Comment by issyl0** [comment]
Thanks both. Going to pair with Alex on this hopefully on Tuesday, as I think I've got it doing the right thing, but testing is proving confusing.

**Comment by issyl0** [comment]
Closing this until I'm back on second-line and have a chance to work on it again.

**Pull request closed without merging**
